/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.Cliente;
import Clases.Mascota;
import Clases.Plan;
import Modelo.modelPlan;
import Controlador.Control;
import java.util.LinkedList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListDataListener;

/**
 *
 * @author User
 */
public class Menu extends javax.swing.JFrame {
    Control controlador;
    LinkedList<Mascota> listaMascotas = new LinkedList<>();
    LinkedList<Plan> listaPlanes = new LinkedList<>();
    LinkedList<Cliente> listaClientes = new LinkedList<>();
    
    
    public Menu() {
        initComponents();
        this.controlador = new Control();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDescripcionPlan = new javax.swing.JTextField();
        txtPrecioPlan = new javax.swing.JTextField();
        cbNombrePlan = new javax.swing.JComboBox<>();
        botonCrearPlan = new javax.swing.JButton();
        botonConsultarPlan = new javax.swing.JButton();
        botonModificarPlan = new javax.swing.JButton();
        botonEliminarPlan = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtCodigoMascota = new javax.swing.JTextField();
        txtNombreMascota = new javax.swing.JTextField();
        txtEdadMascota = new javax.swing.JTextField();
        txtPesoMascota = new javax.swing.JTextField();
        cbEspecie = new javax.swing.JComboBox<>();
        cbPlan = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        cbDueno = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        botonCrearMascota = new javax.swing.JButton();
        BotonConsultarMascota = new javax.swing.JButton();
        botonModificarMascota = new javax.swing.JButton();
        BotonEliminarMascota = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDocumentoCliente = new javax.swing.JTextField();
        txtNombresCliente = new javax.swing.JTextField();
        txtApellidosCliente = new javax.swing.JTextField();
        txtDireccionCliente = new javax.swing.JTextField();
        txtTelefonoCliente = new javax.swing.JTextField();
        cbMascota = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        botonCrearCliente = new javax.swing.JButton();
        botonConsultarCliente = new javax.swing.JButton();
        botonModificarCliente = new javax.swing.JButton();
        botonEliminarCliente = new javax.swing.JButton();

        jButton7.setText("jButton7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nombre");

        jLabel3.setText("Descripción");

        jLabel4.setText("Precio");

        cbNombrePlan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bienestar", "Élite", "Diamante" }));

        botonCrearPlan.setText("Crear");
        botonCrearPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearPlanActionPerformed(evt);
            }
        });

        botonConsultarPlan.setText("Consultar");
        botonConsultarPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarPlanActionPerformed(evt);
            }
        });

        botonModificarPlan.setText("Modificar");
        botonModificarPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarPlanActionPerformed(evt);
            }
        });

        botonEliminarPlan.setText("Eliminar");
        botonEliminarPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarPlanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescripcionPlan)
                            .addComponent(txtPrecioPlan)
                            .addComponent(cbNombrePlan, 0, 186, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(botonCrearPlan)
                        .addGap(18, 18, 18)
                        .addComponent(botonConsultarPlan)
                        .addGap(18, 18, 18)
                        .addComponent(botonModificarPlan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEliminarPlan)))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbNombrePlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDescripcionPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrecioPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCrearPlan)
                    .addComponent(botonConsultarPlan)
                    .addComponent(botonModificarPlan)
                    .addComponent(botonEliminarPlan))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Planes", jPanel1);

        jLabel10.setText("Codigo");

        jLabel11.setText("Nombre");

        jLabel12.setText("Edad");

        jLabel13.setText("Peso");

        jLabel14.setText("Especie");

        cbEspecie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Canino", "Felino" }));

        cbPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPlanActionPerformed(evt);
            }
        });

        jLabel16.setText("Plan");

        jLabel15.setText("Dueño");

        botonCrearMascota.setText("Crear");
        botonCrearMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearMascotaActionPerformed(evt);
            }
        });

        BotonConsultarMascota.setText("Consultar");

        botonModificarMascota.setText("Modificar");

        BotonEliminarMascota.setText("Eliminar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbDueno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCodigoMascota)
                            .addComponent(txtNombreMascota)
                            .addComponent(txtEdadMascota)
                            .addComponent(txtPesoMascota)
                            .addComponent(cbEspecie, 0, 210, Short.MAX_VALUE)
                            .addComponent(cbPlan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(botonCrearMascota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonConsultarMascota)
                        .addGap(18, 18, 18)
                        .addComponent(botonModificarMascota)
                        .addGap(18, 18, 18)
                        .addComponent(BotonEliminarMascota)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCodigoMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtNombreMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtEdadMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(txtPesoMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(cbEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDueno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCrearMascota)
                    .addComponent(BotonConsultarMascota)
                    .addComponent(botonModificarMascota)
                    .addComponent(BotonEliminarMascota))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mascota", jPanel2);

        jLabel5.setText("Documento");

        jLabel6.setText("Nombres");

        jLabel7.setText("Apellidos");

        jLabel8.setText("Dirección");

        jLabel9.setText("Teléfono");

        jLabel17.setText("Mascota");

        botonCrearCliente.setText("Crear");
        botonCrearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearClienteActionPerformed(evt);
            }
        });

        botonConsultarCliente.setText("Consultar");

        botonModificarCliente.setText("Modificar");

        botonEliminarCliente.setText("Eliminar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbMascota, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDocumentoCliente)
                            .addComponent(txtNombresCliente)
                            .addComponent(txtApellidosCliente)
                            .addComponent(txtDireccionCliente)
                            .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(botonCrearCliente)
                        .addGap(18, 18, 18)
                        .addComponent(botonConsultarCliente)
                        .addGap(18, 18, 18)
                        .addComponent(botonModificarCliente)
                        .addGap(18, 18, 18)
                        .addComponent(botonEliminarCliente)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDocumentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNombresCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtApellidosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCrearCliente)
                    .addComponent(botonConsultarCliente)
                    .addComponent(botonModificarCliente)
                    .addComponent(botonEliminarCliente))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cliente", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Planes");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearPlanActionPerformed
        
        String nombre = cbNombrePlan.getSelectedItem().toString();
        String descripcion = txtDescripcionPlan.getText();
        int precio  = Integer.parseInt(txtPrecioPlan.getText());
        
        Plan plan = new Plan(nombre,descripcion,precio);
        if(controlador.CrearPlan(plan)){
                    JOptionPane.showMessageDialog(this, "El plan fue creado exitosamente ");
        }else {
            JOptionPane.showMessageDialog(this, "El plan NOOOOO fue creado ");
        }
        
        
        
    }//GEN-LAST:event_botonCrearPlanActionPerformed

    private void botonCrearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearClienteActionPerformed
        String documento = txtDocumentoCliente.getText();   
        String nombres = txtNombresCliente.getText();
        String apellidos = txtApellidosCliente.getText();
        String direccion = txtDireccionCliente.getText();
        String telefono = txtTelefonoCliente.getText();
        
        Cliente cliente = new Cliente(documento,nombres,apellidos,direccion,telefono);
        JOptionPane.showMessageDialog(this, "Los datos del cliente son: Documento: "+cliente.getDocumento() + " Nombre: "+ cliente.getNombres()+" Apellidos: "+ cliente.getApellidos());
        listaClientes.add(cliente);
        cbDueno.addItem(cliente.getDocumento() + " Nombre: "+ cliente.getNombres()+" Apellidos: "+ cliente.getApellidos());
        
    }//GEN-LAST:event_botonCrearClienteActionPerformed

    private void cbPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPlanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPlanActionPerformed

    private void botonCrearMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearMascotaActionPerformed
        String codigo = txtCodigoMascota.getText();
        String nombre = txtNombreMascota.getText();
        String edad = txtEdadMascota.getText();
        String peso = txtPesoMascota.getText();
        String especie = cbEspecie.getSelectedItem().toString();
        Plan plan; 
        int indice = cbDueno.getSelectedIndex();
        Cliente dueno = listaClientes.get(indice);
        if (cbPlan.getSelectedItem().toString() == "Bienestar"){
            plan = listaPlanes.get(0);
        }else{
            if (cbPlan.getSelectedItem().toString() == "Élite"){
                plan = listaPlanes.get(1);
            }else plan = listaPlanes.get(2);
        }
        Mascota mascota = new Mascota(codigo,nombre,edad,peso,especie,plan,dueno);
        JOptionPane.showMessageDialog(this, "Los datos de la mascota son: codigo: "+mascota.getCodigo()+ " Nombre: "+ mascota.getNombre()+"Plan: "+ mascota.getPlan().getNombre());
        listaMascotas.add(mascota);
        cbMascota.addItem(mascota.getCodigo()+" "+mascota.getNombre());
    }//GEN-LAST:event_botonCrearMascotaActionPerformed

    private void botonConsultarPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarPlanActionPerformed
        String nombre = cbNombrePlan.getSelectedItem().toString();
        Plan p = controlador.buscarPlan(nombre);
        if (p == null){
            JOptionPane.showMessageDialog(this,"Plan no encontrado");
        }else{
            JOptionPane.showMessageDialog(this,"Plan SI encontado");
            txtDescripcionPlan.setText(p.getDescripcion());
            txtPrecioPlan.setText(p.getPrecio() + "");
        }
            
        
        
    }//GEN-LAST:event_botonConsultarPlanActionPerformed

    private void botonModificarPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarPlanActionPerformed
        String nombre = cbNombrePlan.getSelectedItem().toString();
        String descripcion = txtDescripcionPlan.getText();
        int precio  = Integer.parseInt(txtPrecioPlan.getText());
        
        Plan p = new Plan(nombre,descripcion,precio);
        boolean respuesta = controlador.modificarPlan(p);
        if (respuesta){
            JOptionPane.showMessageDialog(this, "Registro Actualizado");
        }else{
            JOptionPane.showMessageDialog(this, "Error actualizando el registro");
        }
    }//GEN-LAST:event_botonModificarPlanActionPerformed

    private void botonEliminarPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarPlanActionPerformed
        String nombre = cbNombrePlan.getSelectedItem().toString();
        boolean borrado = controlador.borrarPlan(nombre);
        if (borrado){
            JOptionPane.showMessageDialog(this, "Si se borró pelaito.");
            this.limpiarCamposPlan();
        }else{JOptionPane.showMessageDialog(this, "Pailas no se borró");}
    }//GEN-LAST:event_botonEliminarPlanActionPerformed
   
    private void limpiarCamposPlan() {
        txtDescripcionPlan.setText("");
        txtPrecioPlan.setText("");
        cbNombrePlan.setSelectedIndex(0);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonConsultarMascota;
    private javax.swing.JButton BotonEliminarMascota;
    private javax.swing.JButton botonConsultarCliente;
    private javax.swing.JButton botonConsultarPlan;
    private javax.swing.JButton botonCrearCliente;
    private javax.swing.JButton botonCrearMascota;
    private javax.swing.JButton botonCrearPlan;
    private javax.swing.JButton botonEliminarCliente;
    private javax.swing.JButton botonEliminarPlan;
    private javax.swing.JButton botonModificarCliente;
    private javax.swing.JButton botonModificarMascota;
    private javax.swing.JButton botonModificarPlan;
    private javax.swing.JComboBox<String> cbDueno;
    private javax.swing.JComboBox<String> cbEspecie;
    private javax.swing.JComboBox<String> cbMascota;
    private javax.swing.JComboBox<String> cbNombrePlan;
    private javax.swing.JComboBox<String> cbPlan;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtApellidosCliente;
    private javax.swing.JTextField txtCodigoMascota;
    private javax.swing.JTextField txtDescripcionPlan;
    private javax.swing.JTextField txtDireccionCliente;
    private javax.swing.JTextField txtDocumentoCliente;
    private javax.swing.JTextField txtEdadMascota;
    private javax.swing.JTextField txtNombreMascota;
    private javax.swing.JTextField txtNombresCliente;
    private javax.swing.JTextField txtPesoMascota;
    private javax.swing.JTextField txtPrecioPlan;
    private javax.swing.JTextField txtTelefonoCliente;
    // End of variables declaration//GEN-END:variables
}
